// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB06xg-dAZ4ndWx-qyehlQrt_hlY3Ew37g',
    appId: '1:212907475445:web:37bade93e4101c711f20bc',
    messagingSenderId: '212907475445',
    projectId: 'test-project1-624da',
    authDomain: 'test-project1-624da.firebaseapp.com',
    storageBucket: 'test-project1-624da.firebasestorage.app',
    measurementId: 'G-T637SZN8RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBZYJlzb-wVnpR-gtUaSVL5MZL783Rm4',
    appId: '1:212907475445:android:8f964f47dab088531f20bc',
    messagingSenderId: '212907475445',
    projectId: 'test-project1-624da',
    storageBucket: 'test-project1-624da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0Yr4wJUb9r14s0342b6CVAXhq6XSqiU',
    appId: '1:212907475445:ios:198fa59ac9f072be1f20bc',
    messagingSenderId: '212907475445',
    projectId: 'test-project1-624da',
    storageBucket: 'test-project1-624da.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA0Yr4wJUb9r14s0342b6CVAXhq6XSqiU',
    appId: '1:212907475445:ios:198fa59ac9f072be1f20bc',
    messagingSenderId: '212907475445',
    projectId: 'test-project1-624da',
    storageBucket: 'test-project1-624da.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB06xg-dAZ4ndWx-qyehlQrt_hlY3Ew37g',
    appId: '1:212907475445:web:f09178c4dd8c3cbc1f20bc',
    messagingSenderId: '212907475445',
    projectId: 'test-project1-624da',
    authDomain: 'test-project1-624da.firebaseapp.com',
    storageBucket: 'test-project1-624da.firebasestorage.app',
    measurementId: 'G-NKKBE0S46N',
  );
}
